version: '3.8'

services:
    backend:
        image: backend
        environment:
          - REDIS_HOST=redis
          - POSTGRES_HOST=db
          - POSTGRES_PASSWORD=salasana
        depends_on:
          - db

    frontend:
        image: frontend

    redis:
        image: redis:7.0.10

    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
          - POSTGRES_PASSWORD=salasana
        volumes:
          - ./database:/var/lib/postgresql/data

    nginx:
        image: nginx:1.23.4
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        depends_on:
          - backend
          - frontend
