version: '3.8'

services:
    backend:
        image: backend
        ports:
          - 8080:8080
        environment:
          - REDIS_HOST=redis
    frontend:
        image: frontend
        ports:
          - 5000:5000
    redis:
        image: redis:7.0.10
